version: '3.8'

services:
  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_ENVIRONMENT=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=auth_user
      - DB_PASSWORD=auth_password
      - DB_NAME=auth_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=supersecretjwtkey
      - JWT_ACCESS_TOKEN_EXPIRATION=15m
      - JWT_REFRESH_TOKEN_EXPIRATION=7d
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_REDIRECT_URL=http://localhost:8080/api/v1/auth/google/callback
      - SECURITY_PASSWORD_MIN_LENGTH=6
      - SECURITY_RATE_LIMIT_REQUESTS=100
      - SECURITY_RATE_LIMIT_DURATION=1m
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_SERVICE_AUTH=http://auth-service:8080
    depends_on:
      - auth-service

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_password
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: